################################################################################
# GKE Labs — Dev Environment Variables
# Project : gke-labs
# Region  : europe-west1
#
# All environment-level inputs are declared here.  Sensitive values (passwords,
# secrets) are intentionally NOT declared as variables; they are generated by
# random_password resources in main.tf so they never appear in tfvars files or
# CI logs.
################################################################################

# ------------------------------------------------------------------------------
# Core project identity
# ------------------------------------------------------------------------------

variable "project_id" {
  type        = string
  description = "GCP project ID into which all resources will be deployed."

  validation {
    condition     = length(var.project_id) > 0
    error_message = "project_id must be a non-empty string."
  }
}

variable "region" {
  type        = string
  default     = "europe-west1"
  description = "GCP region for all regional resources (cluster, SQL, Redis, NAT, etc.)."

  validation {
    condition     = can(regex("^[a-z]+-[a-z]+[0-9]+$", var.region))
    error_message = "region must be a valid GCP region identifier, e.g. europe-west1."
  }
}

# ------------------------------------------------------------------------------
# Naming & environment
# ------------------------------------------------------------------------------

variable "name" {
  type        = string
  default     = "gke-labs"
  description = <<-EOT
    Short resource-name prefix applied to every resource created by this
    environment.  Keep it lowercase, 3-20 chars, hyphens only — no underscores
    or dots, as it is used in DNS-compatible resource names.
  EOT

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{2,19}$", var.name))
    error_message = "name must be 3-20 lowercase alphanumeric characters or hyphens, starting with a letter."
  }
}

variable "env" {
  type        = string
  default     = "dev"
  description = <<-EOT
    Environment label applied to every resource (e.g. dev, staging, prod).
    Used both as a label value and as a suffix in resource names where
    environment isolation is required.
  EOT

  validation {
    condition     = contains(["dev", "staging", "prod"], var.env)
    error_message = "env must be one of: dev, staging, prod."
  }
}

# ------------------------------------------------------------------------------
# Common labels
# All child modules inherit these labels so every GCP resource is consistently
# tagged for cost attribution, automation, and audit.
# ------------------------------------------------------------------------------

variable "labels" {
  type = map(string)
  default = {
    env        = "dev"
    managed-by = "terraform"
    lab        = "gke-labs"
  }
  description = <<-EOT
    Labels applied to every resource created by this environment module.
    GCP label keys and values must be lowercase, start with a letter, and
    contain only letters, digits, hyphens, and underscores (max 63 chars each).
  EOT

  validation {
    condition = alltrue([
      for k, v in var.labels :
      can(regex("^[a-z][a-z0-9_-]{0,62}$", k)) &&
      can(regex("^[a-z0-9_-]{0,63}$", v))
    ])
    error_message = "All label keys and values must follow GCP label naming rules: lowercase, start with a letter (keys), max 63 chars."
  }
}
